[sprites]
game = "random"
variant = "front"
artwork = false
range_start = 1
range_end = 386
pokemon = []

[display]
size = 8
alignment = "center"
gap = 2
background = "#222436"

[icon]
enabled = true
