schema_version = 1

[source]
repository = "https://github.com/PokeAPI/sprites.git"
revision = "c10459b9b0129eaca5c5d9b1cac65336debb1d08"
root = "sprites/pokemon/versions"

[[sets]]
id = "red-blue"
generation = 1
source = "generation-i/red-blue"
dex_end = 151
core_ranges = ["1-151"]

[[sets.variants]]
id = "front"
source = "transparent"

[[sets]]
id = "yellow"
generation = 1
source = "generation-i/yellow"
dex_end = 151
core_ranges = ["1-151"]

[[sets.variants]]
id = "front"
source = "transparent"

[[sets]]
id = "gold"
generation = 2
source = "generation-ii/gold"
dex_end = 251
core_ranges = ["152-251"]

[[sets.variants]]
id = "front"
source = "transparent"

[[sets]]
id = "silver"
generation = 2
source = "generation-ii/silver"
dex_end = 251
core_ranges = ["152-251"]

[[sets.variants]]
id = "front"
source = "transparent"

[[sets]]
id = "crystal"
generation = 2
source = "generation-ii/crystal"
dex_end = 251
core_ranges = ["152-251"]

[[sets.variants]]
id = "front"
source = "transparent"

[[sets.variants]]
id = "front-animated"
source = "animated"
format = "gif"

[[sets]]
id = "ruby-sapphire"
generation = 3
source = "generation-iii/ruby-sapphire"
dex_end = 386
core_ranges = ["252-386"]

[[sets.variants]]
id = "front"
source = "."

[[sets]]
id = "emerald"
generation = 3
source = "generation-iii/emerald"
dex_end = 386
core_ranges = ["252-386"]

[[sets.variants]]
id = "front"
source = "."

[[sets]]
id = "firered-leafgreen"
generation = 3
source = "generation-iii/firered-leafgreen"
dex_end = 386
core_ranges = ["1-151"]

[[sets.variants]]
id = "front"
source = "."
